---
title: "Chromatography Plots"
author: "Greg Bedwell"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/Lab/chromatography/20210216_CPSF6_CPSF5_binding/")
```

```{r}
library(data.table)
library(tidyverse)
```

```{r}
F5 <- data.table::fread(paste0(getwd(), "/F5_trace.txt"), header=FALSE) %>%
  magrittr::set_colnames(c("ev","signal")) %>%
  dplyr::mutate(sample = "CPSF5")

F6 <- data.table::fread(paste0(getwd(), "/F6_trace.txt"), header=FALSE) %>%
  magrittr::set_colnames(c("ev","signal")) %>%
  dplyr::mutate(sample = "CPSF6")

F5.F6 <- data.table::fread(paste0(getwd(), "/F5_F6_trace.txt"), header=FALSE) %>%
  magrittr::set_colnames(c("ev","signal")) %>%
  dplyr::mutate(sample = "CPSF5 + CPSF6")

traces <- rbind(F5, F6, F5.F6)

traces$sample <- factor(traces$sample, levels = c("CPSF5", "CPSF6", "CPSF5 + CPSF6"))

rm(F5, F6, F5.F6)
```


```{r}
plot <- ggplot(traces, aes(x=ev, y=signal, color=sample)) +
  geom_line(size=2) +
  scale_color_manual(values = c("darkblue","darkred","darkgreen"),
                     guide = guide_legend(title.position = "top",
                                          nrow = 1,
                                          title.hjust=0.5)) +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.title=element_text(size=16),
        legend.position = "top",
        legend.text = element_text(size=12),
        legend.title=element_blank(),
        legend.justification="center") +
  scale_y_continuous() +
  scale_x_continuous(limits=c(0,4.5),
                     breaks=c(0, 1.0, 2.0, 3.0, 4.0)) +
  labs(x="Elution Volume (mL)", y="Absorbance (280 nm)")


plot


ggsave(filename=paste0(getwd(), "/chromatogram_plot.tiff"), plot=plot, height=5, width=7, units="in", device="tiff")
```



















